name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Instalar dependências
        run: go mod download

      - name: Rodar testes com cobertura
        run: go test -v -coverprofile=coverage.out ./...

      - name: Mostrar cobertura no terminal
        run: go tool cover -func=coverage.out

      - name: Upload do relatório de cobertura
        uses: actions/upload-artifact@v3
        with:
          name: cobertura-teste
          path: coverage.out
